export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DECREMENT_PRODUCT_INVENTORY = 'DECREMENT_PRODUCT_INVENTORY';
export const INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY';
